### PR TITLE
Fail cake build on Docker build failure.

### LINKED ISSUE #254: Docker builds don't respect failed subprocess exit codes.
See https://github.com/Dotnet-Boxed/Templates/pull/1766/files

### PR DESCRIPTION
**Pull request by frosch95**
Closes #254 

The cake build respect the exit code of the started processes and if the exit code differs to zero, the whole build fails.

### CODE REVIEW

**Comment by ElanHasson** [comment]
Nice! A twofer!

**Comment by frosch95** [comment]
@ElanHasson no luck with the GitHub build actions :-(

**Comment by frosch95** [comment]
@ElanHasson can you have a look why the docker login does not work?

**Comment by ElanHasson** [comment]
Thanks for the contribution @frosch95

**Pull request merged**
